apiVersion: v1
kind: Secret
metadata:
  name: deployer-token
  namespace: dev
  annotations:
    kubernetes.io/service-account.name: deployer
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: deployer-token
  namespace: prod
  annotations:
    kubernetes.io/service-account.name: deployer
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: deployer-token
  namespace: prod
  annotations:
    kubernetes.io/service-account.name: deployer
type: kubernetes.io/service-account-token


